### ISSUE TITLE
Suporte ao ambiente de Sandbox 

### ISSUE THREAD

**Issue by msfidelis** [pjbank/pjbank-python-sdk#5]
Seria interessante adicionar algum mecanismo de suporte para fazer requisições para o ambiente de sandbox https://sandbox.pjbank.com.br do PJBank. Alguma flag ou variável de ambiente que aponte para a urlbase.

**Comment by freudFlintstone** [comment]
As urls padrão estão no arquivo __config__.py. 
As classe PJBankAPI busca url lá e salva em self._url
A propriedade .modo recebe "sandbox" ou  "procucao" e seta a url de acordo. ( Isso no PR #11. Antes era o método configurar() )
Ao instanciar as classes de Recebimento ou Conta Digital, pode-se passar o modo também e o constructor seta a url padrão do ambiente escolhido.

**Comment by msfidelis** [comment]
No SDK de Javascript o cara pode setar um `PJBank.developer(true)` pra habilitar as requisições para o Sandbox. No caso, o usuário teria que alterar o config.py pra utilizar?
